USE [master]
GO

/****** Object:  Database [TOUR]    Script Date: 5/4/2022 1:54:42 PM ******/
CREATE DATABASE [TOUR]
GO
USE [TOUR]
GO

/****** Object:  Table [dbo].[Admin]    Script Date: 5/4/2022 1:54:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ADMIN](
	[MA_ADMIN] [nvarchar](20) NOT NULL,
	[USERNAME] [nvarchar](30) NULL,
	[PASS_ADMIN] [nvarchar](50) NULL,
	[STATUS] [nvarchar](10) NULL,
 CONSTRAINT [PK_Admin] PRIMARY KEY CLUSTERED ([MA_ADMIN] ASC)
)
GO

/****** Object:  Table [dbo].[BINH_LUAN]    Script Date: 5/4/2022 1:54:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BINH_LUAN](
	[MA_BINH_LUAN] [int] NOT NULL,
	[MA_KH] [int] NULL,
	[MA_TOUR] [int] NULL,
	[NOI_DUNG] [nvarchar](50) NULL,
	[VOTE] [int] NULL,
 CONSTRAINT [PK_BinhLuan] PRIMARY KEY CLUSTERED ([MA_BINH_LUAN] ASC)
) 
GO

/****** Object:  Table [dbo].[CHI_TIET_TAG]    Script Date: 5/4/2022 1:54:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CHI_TIET_TAG](
	[MA_TOUR] [int] NULL,
	[MA_TAG] [int] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DON_DAT_TOUR]    Script Date: 5/4/2022 1:54:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DON_DAT_TOUR](
	[MA_DON_DAT] [int] NOT NULL,
	[MA_KHACH_HANG] [int] NOT NULL,
	[MA_TOUR] [int] NULL,
	[NGAY_DAT] [datetime] NULL,
	[TINH_TRANG_THANH_TOAN] [nvarchar](20) NULL,
	[SO_LUONG_VE_DAT] [int] NULL,
	[TONG_TIEN] [int] NULL,
 CONSTRAINT [PK_DonDatVe_1] PRIMARY KEY CLUSTERED ([MA_DON_DAT] ASC) 
) 
GO

/****** Object:  Table [dbo].[KHACH_HANG]    Script Date: 5/4/2022 1:54:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KHACH_HANG](
	[MA_KH] [int] NOT NULL,
	[USERNAME] [nvarchar](50) NOT NULL,
	[PASSWORD] [nvarchar](50) NOT NULL,
	[HO_TEN] [nvarchar](50) NOT NULL,
	[GIOI_TINH] [nvarchar](10) NULL,
	[EMAIL] [nvarchar](50) NOT NULL,
	[DIA_CHI] [nvarchar](50) NULL,
	[SDT] [int] NOT NULL,
	[DIEM_THUONG] [int] NULL,
 CONSTRAINT [PK_KhachHang] PRIMARY KEY CLUSTERED ([MA_KH] ASC)
)
GO

/****** Object:  Table [dbo].[LOAI_TOUR]    Script Date: 5/4/2022 1:54:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LOAI_TOUR](
	[MA_LOAI] [int] NOT NULL,
	[TEN_LOAI] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_LOAI_TOUR] PRIMARY KEY CLUSTERED ([MA_LOAI] ASC)
)
GO

/****** Object:  Table [dbo].[LOAI_VE]    Script Date: 5/4/2022 1:54:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LOAI_VE](
	[MA_LOAI] [int] NOT NULL,
	[TEN_LOAI] [nvarchar](20) NULL,
 CONSTRAINT [PK_LoaiVe] PRIMARY KEY CLUSTERED ([MA_LOAI] ASC)
)
GO

/****** Object:  Table [dbo].[PARTNER]    Script Date: 5/4/2022 1:54:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PARTNER](
	[MA_PARTNER] [int] NOT NULL,
	[USERNAME] [nvarchar](30) NULL,
	[PASSWWORD] [nvarchar](30) NULL,
	[STATUS] [nvarchar](10) NULL,
 CONSTRAINT [PK_PARTNER] PRIMARY KEY CLUSTERED ([MA_PARTNER] ASC)
)
GO

/****** Object:  Table [dbo].[TAG]    Script Date: 5/4/2022 1:54:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TAG](
	[MA_TAG] [int] NOT NULL,
	[TEN_TAG] [nvarchar](50) NULL,
 CONSTRAINT [PK_Tag] PRIMARY KEY CLUSTERED ([MA_TAG] ASC)
)
GO

/****** Object:  Table [dbo].[TOUR]    Script Date: 5/4/2022 1:54:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TOUR](
	[MA_TOUR] [int] IDENTITY(1,1) NOT NULL,
	[MA_LOAI] [int] NOT NULL,
	[TEN_TOUR] [nvarchar](50) NULL,
	[GT_TOUR] [nvarchar](500) NULL,
	[GIA_TOUR] [int] NULL,
	[NOI_DUNG_TOUR] [nvarchar](300) NULL,
	[HINH_ANH] [nvarchar](800) NULL,
	[NGAY_DI] [datetime] NULL,
	[DIEM_DI] [nvarchar](50) NULL,
	[DIEM_DEN] [nvarchar](50) NULL,
	[NGAY_TAO] [datetime] NULL,
 CONSTRAINT [PK_Tour] PRIMARY KEY CLUSTERED ([MA_TOUR] ASC)
)
GO

/****** Object:  Table [dbo].[VE_TOUR]    Script Date: 5/4/2022 1:54:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VE_TOUR](
	[MA_VE] [int] NOT NULL,
	[MA_TOUR] [int] NOT NULL,
	[MA_KH] [int] NULL,
	[NGAY_CO_HIEU_LUC] [datetime] NULL,
	[LOAI_VE] [int] NULL,
	[NGAY_TAO] [datetime] NULL,
	[GIA_VE] [int] NULL,
 CONSTRAINT [PK_VeTour] PRIMARY KEY CLUSTERED ([MA_VE] ASC)
)
GO

INSERT [dbo].[LOAI_TOUR] ([MA_LOAI], [TEN_LOAI]) VALUES (1, N'Du lịch')
INSERT [dbo].[LOAI_TOUR] ([MA_LOAI], [TEN_LOAI]) VALUES (2, N'Thể thao')
INSERT [dbo].[LOAI_TOUR] ([MA_LOAI], [TEN_LOAI]) VALUES (3, N'Giải trí')
GO

INSERT [dbo].[LOAI_VE] ([MA_LOAI], [TEN_LOAI]) VALUES (1, N'Giải Trí')
INSERT [dbo].[LOAI_VE] ([MA_LOAI], [TEN_LOAI]) VALUES (2, N'Thể Thao')
INSERT [dbo].[LOAI_VE] ([MA_LOAI], [TEN_LOAI]) VALUES (3, N'TOUR')
GO

SET IDENTITY_INSERT [dbo].[TOUR] ON 

INSERT [dbo].[TOUR] ([MA_TOUR], [MA_LOAI], [TEN_TOUR], [GT_TOUR], [GIA_TOUR], [NOI_DUNG_TOUR], [HINH_ANH], [NGAY_DI], [DIEM_DI], [DIEM_DEN], [NGAY_TAO]) VALUES (2, 3, N'tham quan địa đạo bến đình', N'đi ca nô', 840000, N'đi ca nô trên sông', N'https://ik.imagekit.io/tvlk/xpe-asset/AyJ40ZAo1DOyPyKLZ9c3RGQHTP2oT4ZXW+QmPVVkFQiXFSv42UaHGzSmaSzQ8DO5QIbWPZuF+VkYVRk6gh-Vg4ECbfuQRQ4pHjWJ5Rmbtkk=/7781982634132/Ben%2520Dinh%2520-%2520Cu%2520Chi%2520Tunnels%2520Tour%2520with%2520Canoe%2520Transfer%2520-%2520Half-Day%2520Tour-450a2f60-b8eb-44dd-a262-e3ce0f93423d.jpeg?_src=imagekit&tr=dpr-2,c-at_max,h-200,q-60,w-300', CAST(N'2022-04-04T00:00:00.000' AS DateTime), N'100A Ung Văn Khiêm', N'bến đình củ chi', CAST(N'2022-04-12T00:00:00.000' AS DateTime))
INSERT [dbo].[TOUR] ([MA_TOUR], [MA_LOAI], [TEN_TOUR], [GT_TOUR], [GIA_TOUR], [NOI_DUNG_TOUR], [HINH_ANH], [NGAY_DI], [DIEM_DI], [DIEM_DEN], [NGAY_TAO]) VALUES (7, 1, N'ăn tối trên sông Sài Gòn', N'ăn tối thực đơn 5 món, du ngoạn trên sông 3 giờ', 500000, N'Ăn tối, ngắm sông', N'https://tausaigon.com.vn/upload/images/bufftet%20%C4%83n%20t%E1%BB%91i%20tr%C3%AAn%20s%C3%B4ng%20S%C3%A0i%20G%C3%B2n.jpg', CAST(N'2022-04-04T00:00:00.000' AS DateTime), N'quận 1', N'bến nhà rồng, quận 1', CAST(N'2022-04-12T00:00:00.000' AS DateTime))
INSERT [dbo].[TOUR] ([MA_TOUR], [MA_LOAI], [TEN_TOUR], [GT_TOUR], [GIA_TOUR], [NOI_DUNG_TOUR], [HINH_ANH], [NGAY_DI], [DIEM_DI], [DIEM_DEN], [NGAY_TAO]) VALUES (1011, 1, N'ăn tối trên sông Sài Gòn', N'ăn tối thực đơn 5 món, du ngoạn trên sông 3 giờ', 1500000, N'Ăn tối, ngắm sông', N'https://1.bp.blogspot.com/-MH6XJmf-C7o/Xtcnba5LYAI/AAAAAAAAnsc/WEnMYmNctqUianS48uuC6Ehq-HWpdzggQCLcBGAsYHQ/s1600/hinh-anh-tphcm%2B%25281%2529.jpg', CAST(N'2022-05-05T00:00:00.000' AS DateTime), N'quận 2', N'bến nhà rồng, quận 2', CAST(N'2022-04-13T00:00:00.000' AS DateTime))
INSERT [dbo].[TOUR] ([MA_TOUR], [MA_LOAI], [TEN_TOUR], [GT_TOUR], [GIA_TOUR], [NOI_DUNG_TOUR], [HINH_ANH], [NGAY_DI], [DIEM_DI], [DIEM_DEN], [NGAY_TAO]) VALUES (1027, 1, N'Thăm nhà thành', N'vui ', 150000, N'ăn uống tham quan', N'https://photo-cms-tpo.zadn.vn/w890/Uploaded/2022/lkyqski002/2016_12_12/9b_GNSK.jpg', CAST(N'2022-06-05T17:00:00.000' AS DateTime), N'360 tân hương', N'45 gò vấp', NULL)
SET IDENTITY_INSERT [dbo].[TOUR] OFF
GO

ALTER TABLE [dbo].[BINH_LUAN]  WITH CHECK ADD  CONSTRAINT [FK_BinhLuan_KhachHang] FOREIGN KEY([MA_KH])
REFERENCES [dbo].[KHACH_HANG] ([MA_KH])
GO
ALTER TABLE [dbo].[BINH_LUAN] CHECK CONSTRAINT [FK_BinhLuan_KhachHang]
GO
ALTER TABLE [dbo].[BINH_LUAN]  WITH CHECK ADD  CONSTRAINT [FK_BinhLuan_Tour] FOREIGN KEY([MA_TOUR])
REFERENCES [dbo].[TOUR] ([MA_TOUR])
GO
ALTER TABLE [dbo].[BINH_LUAN] CHECK CONSTRAINT [FK_BinhLuan_Tour]
GO
ALTER TABLE [dbo].[CHI_TIET_TAG]  WITH CHECK ADD  CONSTRAINT [FK_ChiTietTag_Tag] FOREIGN KEY([MA_TAG])
REFERENCES [dbo].[TAG] ([MA_TAG])
GO
ALTER TABLE [dbo].[CHI_TIET_TAG] CHECK CONSTRAINT [FK_ChiTietTag_Tag]
GO
ALTER TABLE [dbo].[CHI_TIET_TAG]  WITH CHECK ADD  CONSTRAINT [FK_ChiTietTag_Tour] FOREIGN KEY([MA_TOUR])
REFERENCES [dbo].[TOUR] ([MA_TOUR])
GO
ALTER TABLE [dbo].[CHI_TIET_TAG] CHECK CONSTRAINT [FK_ChiTietTag_Tour]
GO
ALTER TABLE [dbo].[DON_DAT_TOUR]  WITH CHECK ADD  CONSTRAINT [FK_DonDatTour_Tour] FOREIGN KEY([MA_TOUR])
REFERENCES [dbo].[TOUR] ([MA_TOUR])
GO
ALTER TABLE [dbo].[DON_DAT_TOUR] CHECK CONSTRAINT [FK_DonDatTour_Tour]
GO
ALTER TABLE [dbo].[DON_DAT_TOUR]  WITH CHECK ADD  CONSTRAINT [FK_DonDatVe_KhachHang] FOREIGN KEY([MA_KHACH_HANG])
REFERENCES [dbo].[KHACH_HANG] ([MA_KH])
GO
ALTER TABLE [dbo].[DON_DAT_TOUR] CHECK CONSTRAINT [FK_DonDatVe_KhachHang]
GO
ALTER TABLE [dbo].[TOUR]  WITH CHECK ADD  CONSTRAINT [FK_Tour_LoaiTour] FOREIGN KEY([MA_LOAI])
REFERENCES [dbo].[LOAI_TOUR] ([MA_LOAI])
GO
ALTER TABLE [dbo].[TOUR] CHECK CONSTRAINT [FK_Tour_LoaiTour]
GO
ALTER TABLE [dbo].[VE_TOUR]  WITH CHECK ADD  CONSTRAINT [FK_VeTour_KhachHang] FOREIGN KEY([MA_KH])
REFERENCES [dbo].[KHACH_HANG] ([MA_KH])
GO
ALTER TABLE [dbo].[VE_TOUR] CHECK CONSTRAINT [FK_VeTour_KhachHang]
GO
ALTER TABLE [dbo].[VE_TOUR]  WITH CHECK ADD  CONSTRAINT [FK_VeTour_LoaiVe] FOREIGN KEY([LOAI_VE])
REFERENCES [dbo].[LOAI_VE] ([MA_LOAI])
GO
ALTER TABLE [dbo].[VE_TOUR] CHECK CONSTRAINT [FK_VeTour_LoaiVe]
GO
ALTER TABLE [dbo].[VE_TOUR]  WITH CHECK ADD  CONSTRAINT [FK_VeTour_Tour] FOREIGN KEY([MA_TOUR])
REFERENCES [dbo].[TOUR] ([MA_TOUR])
GO
ALTER TABLE [dbo].[VE_TOUR] CHECK CONSTRAINT [FK_VeTour_Tour]
GO

/****** Object:  StoredProcedure [dbo].[DeleteTour]    Script Date: 5/4/2022 1:54:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create procedure [dbo].[DeleteTour] 
(@MA_TOUR int)
as
begin
delete from TOUR where MA_TOUR=@MA_TOUR
end
GO

/****** Object:  StoredProcedure [dbo].[InsertTour]    Script Date: 5/4/2022 1:54:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[InsertTour]
@MA_LOAI int,
@TEN_TOUR NVARCHAR(50),
@GT_TOUR NVARCHAR(50),
@GIA_TOUR INT,
@NOI_DUNG_TOUR NVARCHAR(300),
@HINH_ANH NVARCHAR(800),
@NGAY_DI DATETIME ,
@DIEM_DI NVARCHAR(50),
@DIEM_DEN NVARCHAR(50),
@NGAY_TAO DATETIME
AS 
BEGIN
INSERT INTO TOUR (MA_LOAI,TEN_TOUR,GT_TOUR,GIA_TOUR,NOI_DUNG_TOUR,HINH_ANH,NGAY_DI,DIEM_DI,DIEM_DEN,NGAY_TAO)
VALUES (@MA_LOAI,@TEN_TOUR,@GT_TOUR,@GIA_TOUR,@NOI_DUNG_TOUR,@HINH_ANH,@NGAY_DI,@DIEM_DI,@DIEM_DEN,@NGAY_TAO)
END
GO

/****** Object:  StoredProcedure [dbo].[UpdateTour]    Script Date: 5/4/2022 1:54:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
Create Procedure [dbo].[UpdateTour]
(
@MA_TOUR int,
@MA_LOAI int,
@TEN_TOUR NVARCHAR(50),
@GT_TOUR NVARCHAR(50),
@GIA_TOUR INT,
@NOI_DUNG_TOUR NVARCHAR(300),
@HINH_ANH NVARCHAR(800),
@NGAY_DI DATETIME ,
@DIEM_DI NVARCHAR(50),
@DIEM_DEN NVARCHAR(50),
@NGAY_TAO DATETIME

)
AS 
BEGIN
update TOUR set MA_LOAI=@MA_LOAI,
				TEN_TOUR=@TEN_TOUR,
				GT_TOUR=@GT_TOUR,
				GIA_TOUR=@GIA_TOUR,
				NOI_DUNG_TOUR=@NOI_DUNG_TOUR,
				HINH_ANH=@HINH_ANH,
				NGAY_DI=@NGAY_DI,
				DIEM_DI=@DIEM_DI,
				DIEM_DEN=@DIEM_DEN,
				NGAY_TAO=@NGAY_TAO 
				where MA_TOUR=@MA_TOUR
				end
GO
USE [master]
GO
ALTER DATABASE [TOUR] SET  READ_WRITE 
GO
